pypose/lietensor/lietensor.py
pypose/optim/functional.py

Fix bug: LieTensor link, modjac example, and modjac check nan

---

pypose/lietensor/operation.py

This PR may fix the bug reported in #122 .

fix bug of Batching rule not implemented

---

requirements/dev.txt

add requirement for `pypose_sphinx_theme`

---

pypose/module/dynamics.py
test/module/test_dynamics.py

Fix `pytest` warning due to the dynamics model.

fix pytest warning

---

pypose/optim/optimizer.py

The `damping` option for `LM` is moved to `strategy`.
Doc updated

update doc for `optim.LM`

---

docs/source/basics.rst
pypose/__init__.py
pypose/lietensor/__init__.py
pypose/lietensor/basics.py
pypose/lietensor/lietensor.py
pypose/lietensor/operation.py
pypose/lietensor/utils.py
test/basics/test_ops.py

`torch.sign(x)` can return `0` when `x` is zero, which is not expected.

Fix Log bug

---

examples/module/dynamics/cartpole.py
examples/module/dynamics/floquet.py
examples/module/dynamics/neuralnet.py
examples/module/dynamics/readme.md
pypose/module/dynamics.py

Updated examples and some documentation to work with new module.

Updated nls

---

pypose/function/geometry.py

add an option for ``extrinsics`` to be ``None`` in ``reprojerr``

add an option for ``extrinsics`` to be ``None`` in ``reprojerr``

---

docs/source/functions.rst
pypose/function/__init__.py
pypose/function/checking.py
pypose/function/geometry.py
pypose/optim/functional.py
tests/function/test_checking.py
tests/optim/test_jacobian.py
tests/optim/test_optimizer.py

add function `hasnan`
use the function to fix bug in `modjac` mentioned in #237

add `hasnan` and fix bug in `modjac`

---

pypose/sparse/__init__.py
pypose/sparse/sparse_block_tensor.py
test/sparse/test_SBT_bk.py
test/sparse/test_basic.py

Contains the following changes
- in the logic simplification commit, placeholder was removed. This result in a non-trivial speedup once again. 
- test factory is up there. Through a single function, it is able to test multiple operators.

simplify coo2hybrid & test Modularization

---

pypose/module/icp.py
pypose/module/lqr.py
pypose/module/mpc.py
pypose/module/pnp.py

Making import of `nn` in certain modules consistent with the rest of library.

make nn import consistent

---

pypose/lietensor/lietensor.py

Tested on a dev build with pytest. All tests passed.

Fix a minor typo in lietensor.py

---

requirements/runtime.txt

Update pytest to 7.*

---

examples/module/reprojpgo/dataset.py
examples/module/reprojpgo/readme.md

Update the gif in Reprojection error demo's README file.

Fix gif in Reprojection error readme.md

---

pypose/lietensor/operation.py
tests/optim/test_jacobian.py

fix Inv() error when using pp.func.jacrev

---

pypose/module/dynamics.py
pypose/module/lqr.py
tests/module/test_lqr.py

the functions serves LQR and MPC

Sys helper functions

---

pypose/optim/optimizer.py

fix: use reshape instead of view

---

docs/source/functions.rst
pypose/function/geometry.py
tests/function/test_downsample.py

add knn_filter
```
>>> import torch, pypose as pp
>>> points = torch.tensor([[0.,  0.,  0.],
...                        [1.,  0.,  0.],
...                        [0.,  1.,  0.],
...                        [0.,  1.,  1.],
...                        [10., 1.,  1.],
...                        [10., 1., 10.]])
>>> pp.knn_filter(points, k=2, radius=5)
tensor([[0.3333, 0.3333, 0.0000],
[0.3333, 0.3333, 0.0000],
[0.0000, 0.6667, 0.3333],
[0.0000, 0.6667, 0.3333]])
```

knn_filter

---

tests/module/test_ekf.py

set a big initial error for ekf test, avoid sometimes fails in test.

fix sometimes failed in ekf_test

---

pypose/lietensor/lietensor.py
tests/function/test_metric.py

fix operations (Act, Adj, AdjT, Jinvp) for empty tensors.

---

docs/source/modules.rst
pypose/__init__.py
pypose/module/__init__.py
pypose/module/loss.py
tests/module/test_loss.py

GeodesicLoss

---

tests/function/test_metric.py
tests/module/test_lqr.py

fix bugs in pytest (metric and lqr)

fix bugs in pytest (metric and lqr)
